[package]
name = "reth-codecs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
reth-codecs-derive = { path = "./derive", default-features = false }

alloy-eips = { workspace = true, optional = true }
alloy-primitives.workspace = true

bytes.workspace = true

[dev-dependencies]
alloy-eips = { workspace = true, default-features = false, features = ["arbitrary", "serde"] }
alloy-primitives = { workspace = true, features = ["arbitrary", "serde"] }
serde.workspace = true
modular-bitfield.workspace = true
test-fuzz.workspace = true
serde_json.workspace = true

arbitrary = { workspace = true, features = ["derive"] }
proptest.workspace = true
proptest-derive.workspace = true

[features]
default = ["std", "alloy"]
std = ["alloy-primitives/std", "bytes/std"]
alloy = ["alloy-eips"]
optimism = ["reth-codecs-derive/optimism"]
