[package]
name = "reth-network-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Network interfaces"

[lints]
workspace = true

[dependencies]
# reth
reth-primitives.workspace = true
reth-eth-wire.workspace = true
reth-rpc-types.workspace = true
reth-discv4.workspace = true

# eth
enr = { workspace = true, default-features = false, features = ["rust-secp256k1"] }

# misc
thiserror.workspace = true
serde = { workspace = true, features = ["derive"], optional = true }
tokio = { workspace = true, features = ["sync"] }

[features]
default = ["serde"]
serde = ["dep:serde"]
